# Generated by Django 2.0.7 on 2018-11-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team',
            field=models.TextField(blank=True, null=True),
        ),
    ]
