# Generated by Django 2.0.7 on 2018-11-16 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20181116_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officalletter',
            name='user',
        ),
    ]
