# Generated by Django 2.0.7 on 2018-11-18 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_officalletter_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfficalLetter',
        ),
    ]
