# Generated by Django 2.0.7 on 2018-08-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='investors',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
