# Generated by Django 2.0.7 on 2018-09-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_investors'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Headquarter',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='stock_market',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
