# Generated by Django 2.0.7 on 2018-10-26 08:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20181026_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='investors',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
