# Generated by Django 2.0.3 on 2018-03-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('topic', models.CharField(blank=True, max_length=20, null=True)),
                ('details', models.TextField()),
                ('written_by', models.CharField(max_length=20)),
                ('helpfull', models.BooleanField()),
            ],
        ),
    ]
