# Generated by Django 2.0.3 on 2018-03-17 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customercare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgecenter',
            name='topic',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
