# Generated by Django 2.0.3 on 2018-03-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customercare', '0002_auto_20180318_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgecenter',
            name='topic',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
