# Generated by Django 2.0.6 on 2018-07-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customercare', '0004_auto_20180713_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgecenter',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
