# Generated by Django 2.0.6 on 2018-07-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainhubblelook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='topic',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
