# Generated by Django 2.0.6 on 2018-07-23 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainhubblelook', '0002_auto_20180724_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quickword',
            name='topic',
        ),
    ]
