# Generated by Django 2.0.6 on 2018-07-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainhubblelook', '0003_remove_quickword_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickword',
            name='topic',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
