# Generated by Django 2.0.6 on 2018-07-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainhubblelook', '0004_quickword_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickword',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
