# Generated by Django 2.0.6 on 2018-08-12 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainhubblelook', '0004_addproduct_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
