# Generated by Django 2.0.6 on 2018-07-29 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainhubblelook', '0005_auto_20180729_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quickword',
            old_name='description',
            new_name='micro_thought',
        ),
    ]
