# Generated by Django 2.0.7 on 2018-09-17 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainhubblelook', '0005_article_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickword',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
