# Generated by Django 2.0.6 on 2018-07-29 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainhubblelook', '0006_auto_20180729_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='description',
            new_name='micro_article',
        ),
    ]
