# Generated by Django 2.0.6 on 2018-07-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainhubblelook', '0009_auto_20180729_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickword',
            name='Initial_keyword_choices',
            field=models.CharField(blank=True, choices=[('I think', 'I THINK'), ('Prototype', 'FEEDBACK'), ('Feedback', 'GOOD PART'), ('Good part', 'BAD PART'), ('Bad part', 'PROTOTYPE'), ('Info', 'INFO'), ('Review', 'REVIEW'), ('Ask', 'ASK'), ('Financial market', 'FINANCIAL MARKET')], default='I think', max_length=300, null=True),
        ),
    ]
